#! /bin/sh
#can get prop of a window
exec xprop -notype
    -f WM_NAME 8s ':n title =? $0n'
    -f WM_CLASS 8s ':n appName =? $0n className =? $1n'
    -f WM_WINDOW_ROLE 8s ':n stringProperty "WM_WINDOW_ROLE" =? $0n'
    WM_NAME WM_CLASS WM_WINDOW_ROLE
    ${1+"$@"}
